### ISSUE TITLE
Unable to actually build the package with makepkg after checking with updvcspkg

### ISSUE THREAD

**Issue by ThePirate42** [egormanga/updvcspkg#1]
After running updvcspkg, trying to build the package with makepkg fails with a an error in git. This is my command line:

```
[pietro@notgreen builds]$ updvcspkg
leagueoflegends-git 0.11.22.r13.gf472d5e-1 -> 0.11.22.r15.gfd0ffec-1
winetricks-git 20211230.r0.gb458acf7-1 -> 20211230.r2.g48ed598e-1
[pietro@notgreen builds]$ auracle clone leagueoflegends-git
update complete: /home/pietro/builds/leagueoflegends-git
[pietro@notgreen builds]$ cd ./leagueoflegends-git
[pietro@notgreen leagueoflegends-git]$ makepkg -sirc
==> Creazione del pacchetto: leagueoflegends-git 0.11.22.r13.gf472d5e-1 (lun 24 gen 2022, 18:05:24)
==> Controllo delle dipendenze durante l'avvio in corso...
==> Controllo delle dipendenze durante la compilazione in corso...
==> Download dei sorgenti in corso...
  -> Aggiornamento del repository leagueoflegends-git git in corso...
Recupero di origin in corso
==> Validazione di source file con sha256sums...
    leagueoflegends-git ... Ignorato
==> Estrazione dei sorgenti in corso...
  -> Creazione di una copia di lavoro del repository leagueoflegends-git git in corso...
error: la directory oggetti /tmp/updvcspkg/leagueoflegends-git/leagueoflegends-git/objects non esiste; controlla .git/objects/info/alternates
fatal: '/tmp/updvcspkg/leagueoflegends-git/leagueoflegends-git' does not appear to be a git repository
fatal: Impossibile leggere dal repository remoto.

Assicurati di disporre dei privilegi d'accesso corretti
e che il repository esista.
==> ERRORE: Impossibile creare una copia di lavoro del repository leagueoflegends-git git
    L'operazione sta per essere interrotta...
```
I've just realized that I'm not using english 😅 I'll try to provide you the errors in english when I have the time, but for now I'll post this anyway (it's italian).

**Comment by egormanga** [comment]
Thanks for the feedback!

You're not supposed to build from these repositories. They're cloned temporarily just to perform the version check, and should be removed automatically just before the command returns.
If you want to save bandwidth, you should use `$SRCDEST` in your `makepkg.conf` to set up source caching.

As for the language, just prepend `LANG=` (with a space) to the actual command.

**Comment by ThePirate42** [comment]
I think that the problem is that I set
```
BUILDDIR=/tmp/makepkg
```
in makepkg.conf

Since your temporary repo is made with makepkg, and makepkg downloads the source in BUILDDIR by default (if SRCDEST isn't set), your final command 
```
rm -rf "$TMPDIR"
```
doesn't remove the repo, which is in `/tmp/makepkg`

**Comment by egormanga** [comment]
Oh right, didn't quite think it out! Will be fixed in a next release.

**Comment by ThePirate42** [comment]
As a workaround, rebooting my system (thus removing all temporary files) solves the problem. Probably deleting them manually also works.
