### ISSUE TITLE
When will you publish a release with the patch?

### ISSUE THREAD

**Issue by ThePirate42** [egormanga/updvcspkg#3]
I really need the patched version, and I was hoping to use the AUR version and not a personal copy, but there hasn't been activity since my pull request.

**Comment by egormanga** [comment]
Oops! Sorry. I somehow managed to forgot about that.

I'll release it now.

Maybe I will also roll out an auto-deployment script later to mitigate that in the future.

**Comment by egormanga** [comment]
The new release is now live on AUR. Thank you for contribution.

**Comment by ThePirate42** [comment]
Thank you!
